### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by zzlune** [RabbyHub/Web3AppStoreProtocol#1]
Hi Rabby Team,

Thanks for your work.
And when I looked at the description of this protocol, I have some questions,
1. The process of this protocol is similar to the Chrome Extension Store? The difference is this protocol is permissionless, but for the chrome extension, the user also can reload the source file locally
2. When the users want to access the web3 app, they must install a lot of packages used in this app locally. Similar to the React Web App, users must 'yarn install&&yarn start' and then the web app will run on their local environment.

**Comment by vvvvvv1vvvvvv** [comment]
1. Yep, you can imagine this protocol as a Chrome Extension Store but decentralized and each dapp is a Chrome Extension
2. Protocol doesn't  define the code in files should be source code or bundle code actually, but in most case it should be bundle code so App Store just download the code and run a HTTP server locally

**Comment by zzlune** [comment]
> 1. Yep, you can imagine this protocol as a Chrome Extension Store but decentralized and each dapp is a Chrome Extension
> 2. Protocol doesn't  define the code in files should be source code or bundle code actually, but in most case it should be bundle code so App Store just download the code and run a HTTP server locally

@vvvvvv1vvvvvv Thanks for your reply
One thing I worry about is that maybe it is difficult to run it in their local environment even though the bundle code.
And will you promote this protocol to the app developer or other products?

**Comment by vvvvvv1vvvvvv** [comment]
> One thing I worry about is that maybe it is difficult to run it in their local environment even though the bundle code

I don't think user need to worry about it since the protocol is face to developers who want to build an App Store base this protocol

> And will you promote this protocol to the app developer or other products?

Probably, we will do things like that after this protocol perfectly

**Comment by afiiijooon** [comment]
> 1. Yep, you can imagine this protocol as a Chrome Extension Store but decentralized and each dapp is a Chrome Extension
> 2. Protocol doesn't  define the code in files should be source code or bundle code actually, but in most case it should be bundle code so App Store just download the code and run a HTTP server locally

**Comment by arty000** [comment]
> > 1. Yep, you can imagine this protocol as a Chrome Extension Store but decentralized and each dapp is a Chrome Extension
> > 2. Protocol doesn't  define the code in files should be source code or bundle code actually, but in most case it should be bundle code so App Store just download the code and run a HTTP server locally
> 
>
